$$\LARGE\color{purple}{第三次作业}$$


$1、 Householder 与 Givens 在矩阵分解中的比较$ 

$$a$$

Householder变换：$O(\frac{4}{3}n^3\approx n^3)$

Givens旋转：$O(\approx n^2)$

$$b$$

In [49]:
import numpy as np
import math
import pandas
#Householder 变换
def Householder(A):
    n=len(A)
    R=np.copy(A)
    Q=np.identity(n)
    for i in range(n-1):
        u=R[i:,i]
        a=np.linalg.norm(u)
        e=[0 for j in range(n-i)]
        e[0]=1
        v=np.matrix(u)-a*np.matrix(e)
        Q_=np.identity(n)
        Q_[i:,i:]=Q_[i:,i:]-2*np.dot(v.T,v)/np.linalg.norm(v)**2
        R=np.dot(Q_,R)
        Q=np.dot(Q,Q_)
    return(Q,R)
q0=Householder(np.matrix("1 3 2;3 1 4;1 3 5"))[0]
q1=Householder(np.matrix("1 3 2;3 1 4;1 3 5"))[1]
print("输入的矩阵A:")
print(np.matrix("1 3 2;3 1 4;1 3 5"))
print("对A进行QR分解：")
print(q0)#Q
print(q1)#R
print("验证A=QR")
print(np.dot(q0,q1))
print("验证Q矩阵的正交性:Q^TQ=I")
print(np.dot(q0.T,q0))

输入的矩阵A:
[[1 3 2]
 [3 1 4]
 [1 3 5]]
对A进行QR分解：
[[ 3.01511345e-01  6.39602149e-01  7.07106781e-01]
 [ 9.04534034e-01 -4.26401433e-01  6.15902987e-17]
 [ 3.01511345e-01  6.39602149e-01 -7.07106781e-01]]
[[ 3.31662479e+00  2.71360210e+00  5.72871555e+00]
 [ 1.11542807e-16  3.41121146e+00  2.77160931e+00]
 [ 2.54156251e-16  3.95456030e-16 -2.12132034e+00]]
验证A=QR
[[1. 3. 2.]
 [3. 1. 4.]
 [1. 3. 5.]]
验证Q矩阵的正交性:Q^TQ=I
[[1.00000000e+00 1.23563367e-16 2.06050670e-16]
 [1.23563367e-16 1.00000000e+00 1.26882787e-16]
 [2.06050670e-16 1.26882787e-16 1.00000000e+00]]


$$c$$

In [52]:
import numpy as np
import math
import pandas
#Givens旋转
def Givens(A):
    n=len(A)
    R=np.copy(A)
    Q=np.identity(n)
    for i in range(1,n):
        for j in range(i):
            if(R[i][j]!=0):
                r=math.sqrt(R[i][j]**2+R[j][j]**2)
                c=R[j][j]/r
                s=-R[i][j]/r
                G=np.identity(n)
                G[i][j]=s
                G[j][i]=-s
                G[i][i]=G[j][j]=c
                R=np.dot(G,R)
                Q=np.dot(Q,G.T)
    return(Q,R)
q2=Givens(np.matrix("1 3 2;3 1 4;1 3 5"))[0]
q3=Givens(np.matrix("1 3 2;3 1 4;1 3 5"))[1]
print("输入的矩阵A:")
print(np.matrix("1 3 2;3 1 4;1 3 5"))
print("对A进行QR分解：")
print(q2)#Q
print(q3)#R
print("验证A=QR")
print(np.dot(q2,q3))
print("验证Q矩阵的正交性:Q^TQ=I")
print(np.dot(q2.T,q2))

输入的矩阵A:
[[1 3 2]
 [3 1 4]
 [1 3 5]]
对A进行QR分解：
[[ 3.01511345e-01  6.39602149e-01  7.07106781e-01]
 [ 9.04534034e-01 -4.26401433e-01 -5.33365554e-17]
 [ 3.01511345e-01  6.39602149e-01 -7.07106781e-01]]
[[ 3.31662479e+00  2.71360210e+00  5.72871555e+00]
 [-7.44760246e-17  3.41121146e+00  2.77160931e+00]
 [ 8.23363432e-17 -1.73967670e-17 -2.12132034e+00]]
验证A=QR
[[1. 3. 2.]
 [3. 1. 4.]
 [1. 3. 5.]]
验证Q矩阵的正交性:Q^TQ=I
[[ 1.00000000e+00  3.94778328e-17 -7.24618903e-17]
 [ 3.94778328e-17  1.00000000e+00 -1.01136563e-16]
 [-7.24618903e-17 -1.01136563e-16  1.00000000e+00]]


$$d$$

In [18]:
#输出数据时用到了文件包“prettytable.py”
import numpy as np
import math
import pandas
import time
from prettytable import PrettyTable
def Householder(A):
    n=len(A)
    R=np.copy(A)
    Q=np.identity(n)
    for i in range(n-1):
        u=R[i:,i]
        a=np.linalg.norm(u)
        e=[0 for j in range(n-i)]
        e[0]=1
        v=np.matrix(u)-a*np.matrix(e)
        Q_=np.identity(n)
        Q_[i:,i:]=Q_[i:,i:]-2*np.dot(v.T,v)/np.linalg.norm(v)**2
        R=np.dot(Q_,R)
        Q=np.dot(Q,Q_)
    return(Q,R)
def Givens(A):
    n=len(A)
    R=np.copy(A)
    Q=np.identity(n)
    for i in range(1,n):
        for j in range(i):
            if(R[i][j]!=0):
                r=math.sqrt(R[i][j]**2+R[j][j]**2)
                c=R[j][j]/r
                s=-R[i][j]/r
                G=np.identity(n)
                G[i][j]=s
                G[j][i]=-s
                G[i][i]=G[j][j]=c
                R=np.dot(G,R)
                Q=np.dot(Q,G.T)
    return(Q,R)
t1=[]
for i in range(20):
    start1=time.clock()
    B=np.random.uniform(-1,1,36).reshape(6,6)
    Householder(B)
    end1=time.clock()
    t1.append(end1-start1)
t=[]
for i in range(20):
    start=time.clock()
    B=np.random.uniform(-1,1,36).reshape(6,6)
    Givens(B)
    end=time.clock()
    t.append(end-start)
col = PrettyTable()
col.add_column("Householder镜面变换时间：",t1)
col.add_column("Givens旋转变换时间：",t)
print(col)

+---------------------------+------------------------+
| Householder镜面变换时间： |  Givens旋转变换时间：  |
+---------------------------+------------------------+
|   0.0008005699785371689   | 0.00034725578120742284 |
|   0.0006513184173400077   | 0.0003006413969615096  |
|   0.00039942967941897223  | 0.0002506057733171474  |
|   0.0003754810047666979   | 0.00019073408680014836 |
|   0.0003874553422065219   | 0.00018945112196888658 |
|   0.0003720597655956226   | 0.00018987877706422296 |
|   0.0003682108715565846   | 0.00018816815736499848 |
|   0.00037548100499407155  | 0.0002155380711883481  |
|   0.0003746256950307725   | 0.00019073408680014836 |
|   0.00038104051850496035  | 0.00019116174166811106 |
|   0.0013270131639728788   | 0.00018816815736499848 |
|   0.0005418387622739829   | 0.00018945112196888658 |
|   0.0004178188403329841   |  0.000293371263296649  |
|   0.00041739118523764773  | 0.00020484669857978588 |
|   0.0005080540247490717   | 0.00018945112196888658 |
|   0.000384461757903409

$由上述时间检测知：Givens旋转变换速度快于Householder变换。$

$2、幂次法求矩阵的最大模的本征值与本征矢$

$$a$$

将$x(t)=xe^{-iwt}$代入$\frac{d^2x(t)}{d^2t}=-A\cdot x(t)$得\begin{eqnarray}-w^2e^{-iwt}x&=&-e^{-iwt}A\cdot x\\ A\cdot x&=&\lambda x\\&=&w^2x\end{eqnarray}

$$b$$

In [56]:
import numpy as np
import math
import pandas
import time
from prettytable import PrettyTable
#生成矩阵A
def delta (i,j):
    if(i==j):
        return(1)
    else:
        return(0)
def F1(N1):
    C=[]
    for i in range(N1):
        for j in range(N1):
                C.append(delta(i-1,j)+delta(i+1,j)-2*delta(i,j))
    B=np.matrix(C).reshape(N1,N1)
    B[0,N1-1]=B[N1-1,0]=1
    return(B)
#随机产生单位矢量Q_0
def Q_0(N2):
    Q=np.random.uniform(0,10,N2)
    return(np.matrix(Q)/np.linalg.norm(Q))
#幂次法
def F2(N3):
    A=F1(N3)
    q=Q_0(N3)
    z_i=np.dot(A,q.T)
    q_i=z_i/np.linalg.norm(z_i)
    v_i=np.dot(np.dot(q_i.T,A),q_i)
    for i in range(10000):
        z_i=np.dot(A,q_i)
        q_i=z_i/np.linalg.norm(z_i)
        v_i=np.dot(np.dot(q_i.T,A),q_i)
    return(v_i[0,0],q_i)
print("本征值：%.6f"%F2(10)[0])
print("本征矢量：")
print(F2(10)[1])

本征值：-4.000000
本征矢量：
[[ 0.31622777]
 [-0.31622777]
 [ 0.31622777]
 [-0.31622777]
 [ 0.31622777]
 [-0.31622777]
 [ 0.31622777]
 [-0.31622777]
 [ 0.31622777]
 [-0.31622777]]


证明：\begin{eqnarray}q_0&=&\sum_{i=1}^{n}\alpha_iv_i\\q_1&=&A\sum_{i=1}^n \alpha_iv_i=\sum_{i=1}^n\alpha_i\lambda_iv_i\\……\\q_k&=&\lambda_1^k(\alpha_1v_1+\alpha_2(\frac{\lambda_2}{\lambda_1})^kv_2+\alpha_3(\frac{\lambda_3}{\lambda_1})^kv_3+……)\\\lim_{k\to\infty}q_k&=&\lambda_1^k\alpha_1v_1\end{eqnarray}
由$$q_k=\lambda_1^k(\alpha_1v_1+\alpha_2(\frac{\lambda_2}{\lambda_1})^kv_2+\alpha_3(\frac{\lambda_3}{\lambda_1})^kv_3+……)$$知$$((\alpha_1\lambda_1^k)^2+(\alpha_2(\frac{\lambda_2}{\lambda_1})^k)^2+……)^{1/2}=1$$当$k\to\infty$时$$\alpha_1\lambda_1^k=1$$即$$\lim_{k\to\infty}q_k=v_1$$而本征值：$$\lim_{k\to\infty}v_k=\lim_{k\to\infty}q_k^TAq_k=v_1^TAv_1=\lambda_1\\得证$$

